- hosts: localhost
  vars:
    region: eu-west-2
    flavor: t2.micro
    key: Key2
    image: ami-0eab3a90fc693af19
    vpc: vpc-bdf187d5
  gather_facts: False

  tasks:
    - name: Create subnet for database servers