- hosts: localhost
  vars:
    region: eu-west-2
    flavor: t2.micro
    key: Key2
    image: ami-0eab3a90fc693af19
    vpc: vpc-bdf187d5
  gather_facts: False

  tasks:
    - name: Info
      ec2_instance_facts:
        region: "{{ vars.region }}"
        filters:
          "tag:type": srvWeb
      register: test_web
    
    - debug:
        var: test_web.instances[0].instance_id

