- hosts: localhost
  vars:
    region: eu-west-3
    flavor:
    subnetAdm:
    subnetWeb:
    subnetApp:
    subnetBdd:
    groupAdm:
    groupWeb:
    groupApp:
    groupBdd:
    key: Key1
    image:
  gather_facts: False

  tasks:
    - name: Creat Administration VM
      ec2:
        key_name: "{{ vars.key }}"
        instance_type: "{{ vars.flavor }}"
        image: "{{ vars.image }}"
        wait: yes
        group: 
        count: 1
        vpc_subnet_id: subnet-29e63245
        assign_public_ip: yes